package:
  name: xsd-marlo
  version: 4.0.0

source:
  path: releases/xsd-4.0.0-i686-macosx # [osx]
  path: releases/xsd-4.0.0-i686-linux-gnu # [linux32]
  path: releases/xsd-4.0.0-x86_64-linux-gnu # [linux64]
  path: releases/xsd-4.0.0-i686-windows # [win]

build:
  number: 1

requirements:
  build:
    - xerces-c
    - expat
  run:
    - xerces-c
    - expat

about:
  home: https://www.codesynthesis.com/products/xsd/download.xhtml
  license: "GPL v2"
  summary: "XSD runtime library"
  recipe_author: "S.P. Mohanty"
  author_email: "sharada.mohanty@epfl.ch"

extra:
  maintainers:
    - S.P. Mohanty <sharada.mohanty@epfl.ch>
